### ISSUE TITLE
Experimental Setup

### ISSUE THREAD

**Issue by SanghyeokSon** [chunmeifeng/DiffTPT#3]
First of all, thank you for sharing your impressive work.

I have several questions about the experimental setup.

1. 
In section 4.1 Experimental Setup of the paper, it is noted that " to investigate the effectiveness of our method with regard to cross-datasets generalization, ImageNet is used as a comprehensive source dataset".
What does the 'used as a source dataset' mean? 
As I understand it, since the DiffTPT is a test-time tuning method, it needs an instance-wise tuned prompt on the target dataset to evaluate.

2.
In section 4.1 Experimental Setup of the paper, it is noted that "1,000 test images are randomly selected from all the classes to evaluate all the methods".
However, some datasets have samples much smaller than 1,000 for classes.

I look forward to receiving your reply.
Sincerely,

**Comment by chunmeifeng** [comment]
Hi thanks for your interest.

For the first question. The objective of Cross-Datasets Generalization is
to investigate how our proposed method and baselines generalize from
ImageNet to the 10 fine-grained datasets.
The phrase "ImageNet is used as a comprehensive source dataset" implies
that in this experiment, the CoOp and Co-CoOp are tuned on ImageNet using
16-shot training data per category.
For the second question, we've randomly selected a total of 1,000 images
from across all categories for testing.
It's crucial to note that we didn't pick 1,000 images from each category.

Best

Sanghyeok ***@***.***> 于2023年10月22日周日 17:00写道：

**Comment by SanghyeokSon** [comment]
Thank you for your prompt reply!

**Comment by chunmeifeng** [comment]
You r welcome ！

Sanghyeok ***@***.***>于2023年10月22日 周日下午7:35写道：
