### ISSUE TITLE
Paired Generation Possible?

### ISSUE THREAD

**Issue by xuhangc** [chunmeifeng/DiffTPT#5]
Hi, thank you for your great work. I am amazed by the your model's effect in data augmentation. I am currently engaged in a project that necessitates the use of paired images—one to act as degraded input and the other as ground truth. I am interested in knowing whether your model supports the generation of such paired images, as it could greatly benefit my work.

**Comment by chunmeifeng** [comment]
Thank you for your interest. Can you describe your problem in detail?

Nick Chen ***@***.***> 于2023年12月11日周一 11:12写道：

**Comment by xuhangc** [comment]
Hello, using shadow removal as an example, my inputs comprise pairs of images with and without shadows. If I aim to augment the data, both the shadowed and shadow-free images must undergo simultaneous cropping, resizing, and other transformations. I am curious whether your model can accommodate such a process.

**Comment by chunmeifeng** [comment]
I understand that your task is to remove shadows, so your input and GT are
paired.
One way you can augment the GT directly and add shadows to them is via
customized image generation as new input.
Another way is to directly augment the input by adding different shadows to
the original GT by customized image generation.

Nick Chen ***@***.***> 于2023年12月13日周三 13:36写道：

**Comment by xuhangc** [comment]
ok got it.
